ALTER TABLE contracts ADD COLUMN `risk` VARCHAR(20) NOT NULL DEFAULT '未审核';
ALTER TABLE contracts ADD COLUMN `risk_count` INT NOT NULL DEFAULT 0;
ALTER TABLE contracts ADD COLUMN `risk_level` VARCHAR(20) NOT NULL DEFAULT 'green';
